* AI HELP USED THROUGHOUT
IDENTIFICATION DIVISION.
PROGRAM-ID. CAESAR-CIPHER.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 ORIGINAL-STR PIC X(100) VALUE "OPERATION DAYBREAK".
01 ENCRYPTED-STR PIC X(100).
01 DECRYPTED-STR PIC X(100).
01 MAX-SHIFT-VALUE PIC 99 VALUE 2.
01 DUMMY PIC X(100).
01 SHIFTAMOUNT PIC 99 VALUE 3.
01 TEMP PIC 99.

LINKAGE SECTION.
01 LNK-STR PIC X(100).
01 LNK-SHIFTAMOUNT PIC 99.
01 LNK-ENCRYPTED-STR PIC X(100).
01 LNK-DECRYPTED-STR PIC X(100).
01 LNK-MAX-SHIFT-VALUE PIC 99.
01 LNK-DUMMY PIC X(100).
01 EFFECTIVE-SHIFT PIC 99.
01 RESULT PIC 999.
01 I PIC 99.

PROCEDURE DIVISION.
DISPLAY "Starting multi".

CALL 'ENCRYPT' USING BY REFERENCE ORIGINAL-STR, BY VALUE SHIFTAMOUNT, BY REFERENCE ENCRYPTED-STR.
DISPLAY "Encrypted String: " ENCRYPTED-STR.

CALL 'DECRYPT' USING BY REFERENCE ENCRYPTED-STR, BY VALUE SHIFTAMOUNT, BY REFERENCE DECRYPTED-STR.
DISPLAY "Decrypted String: " DECRYPTED-STR.

CALL 'SOLVE' USING BY REFERENCE ORIGINAL-STR, BY VALUE MAX-SHIFT-VALUE, BY REFERENCE ENCRYPTED-STR.


STOP RUN.

ENCRYPT SECTION.
ENTRY 'ENCRYPT' USING BY REFERENCE LNK-STR, BY VALUE LNK-SHIFTAMOUNT, BY REFERENCE LNK-ENCRYPTED-STR.
    COMPUTE TEMP = LNK-SHIFTAMOUNT / 26
    COMPUTE EFFECTIVE-SHIFT = LNK-SHIFTAMOUNT - (TEMP * 26)
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > FUNCTION LENGTH(LNK-STR)
        IF LNK-STR(I:1) >= "A" AND LNK-STR(I:1) <= "Z"
            COMPUTE RESULT = FUNCTION ORD(LNK-STR(I:1)) + EFFECTIVE-SHIFT
            IF RESULT > FUNCTION ORD("Z")
                COMPUTE RESULT = RESULT - 26
            END-IF
            MOVE FUNCTION CHAR(RESULT) TO LNK-ENCRYPTED-STR(I:1)
        ELSE
            MOVE LNK-STR(I:1) TO LNK-ENCRYPTED-STR(I:1)
        END-IF
    END-PERFORM
    GOBACK.

DECRYPT SECTION.
ENTRY 'DECRYPT' USING BY REFERENCE LNK-STR, BY VALUE LNK-SHIFTAMOUNT, BY REFERENCE LNK-DECRYPTED-STR.
    COMPUTE TEMP = LNK-SHIFTAMOUNT / 26
    COMPUTE EFFECTIVE-SHIFT = LNK-SHIFTAMOUNT - (TEMP * 26)
        PERFORM VARYING I FROM 1 BY 1 UNTIL I > FUNCTION LENGTH(LNK-STR)
        IF LNK-STR(I:1) >= "A" AND LNK-STR(I:1) <= "Z"
            COMPUTE RESULT = FUNCTION ORD(LNK-STR(I:1)) - EFFECTIVE-SHIFT
            IF RESULT < FUNCTION ORD("A")
                COMPUTE RESULT = RESULT + 26
            END-IF
            MOVE FUNCTION CHAR(RESULT) TO LNK-DECRYPTED-STR(I:1)
        ELSE
            MOVE LNK-STR(I:1) TO LNK-DECRYPTED-STR(I:1)
        END-IF
    END-PERFORM
    GOBACK.

SOLVE SECTION.
ENTRY 'SOLVE' USING BY REFERENCE LNK-STR, BY VALUE LNK-MAX-SHIFT-VALUE, BY REFERENCE LNK-DUMMY.
    DISPLAY "Trying all shifts:"
    PERFORM VARYING I FROM LNK-MAX-SHIFT-VALUE BY -1 UNTIL I < 0
        DISPLAY "CAESAR " I ":"
        CALL 'ENCRYPT' USING BY REFERENCE LNK-STR, BY VALUE I, BY REFERENCE LNK-DUMMY
        DISPLAY LNK-DUMMY
    END-PERFORM
    GOBACK.

END PROGRAM CAESAR-CIPHER.